const $ = (s) => document.querySelector(s), $$ = (s) => document.querySelectorAll(s);
const products = {classic:{name:'Kerala-style Nendran chips',price:149},pepper:{name:'Cracked Pepper chips',price:159},jaggery:{name:'Jaggery Glaze chips',price:169},chilli:{name:'Curry Leaf Chilli chips',price:159}};
let cart = JSON.parse(localStorage.getItem('kora-cart') || '{}');
if(typeof cart === 'number') cart = cart ? {classic:cart} : {};
let liked = sessionStorage.getItem('kora-liked') === 'true';
const money = n => `₹${n.toLocaleString('en-IN')}`;
function totalItems(){return Object.values(cart).reduce((a,b)=>a+b,0)}
function render(){const count=totalItems(),sub=Object.entries(cart).reduce((sum,[id,q])=>sum+products[id].price*q,0);$$('.cart-count').forEach(e=>e.textContent=count);$('.cart-filled').style.display=count?'flex':'none';$('.cart-empty').style.display=count?'none':'flex';$('.subtotal').textContent=money(sub);$('.cart-items').innerHTML=Object.entries(cart).map(([id,q])=>`<div class="cart-item"><img src="assets/nendran-hero.png" alt="${products[id].name}"><div><h3>${products[id].name}</h3><p>200g pouch</p><div class="quantity"><button data-action="minus" data-id="${id}">−</button><span>${q}</span><button data-action="plus" data-id="${id}">+</button></div></div><div class="item-side"><strong>${money(products[id].price*q)}</strong><button class="remove" data-action="remove" data-id="${id}">Remove</button></div></div>`).join('');localStorage.setItem('kora-cart',JSON.stringify(cart))}
function add(id){cart[id]=(cart[id]||0)+1;render();cartOpen()}
function renderLiked(){$$('.heart').forEach(e=>{e.classList.toggle('active',liked);const icon=e.querySelector('span');if(icon)icon.textContent=liked?'♥':'♡';else e.textContent=liked?'♥':'♡'});sessionStorage.setItem('kora-liked',liked)}
function cartOpen(open=true){document.body.classList.toggle('cart-open',open)}
$$('.add-btn').forEach(b=>b.addEventListener('click',()=>add('classic')));$$('.add-product').forEach(b=>b.addEventListener('click',()=>add(b.dataset.id)));$$('.heart').forEach(b=>b.addEventListener('click',()=>{liked=!liked;renderLiked()}));$('.cart-link').addEventListener('click',()=>cartOpen());$$('.close-cart,.overlay').forEach(b=>b.addEventListener('click',()=>cartOpen(false)));$('.cart-items').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=b.dataset.id;if(b.dataset.action==='plus')cart[id]++;if(b.dataset.action==='minus')cart[id]--;if(b.dataset.action==='remove'||cart[id]<1)delete cart[id];render()});$$('.image-trigger').forEach(el=>el.addEventListener('click',()=>document.body.classList.add('lightbox-open')));$('.close-lightbox').addEventListener('click',()=>document.body.classList.remove('lightbox-open'));$('.lightbox').addEventListener('click',e=>{if(e.target===e.currentTarget)document.body.classList.remove('lightbox-open')});$('.menu-btn').addEventListener('click',()=>$('.nav').classList.toggle('menu-open'));$$('.nav nav a').forEach(a=>a.addEventListener('click',()=>$('.nav').classList.remove('menu-open')));render();renderLiked();
